export default {
  zh: {
    sendVerifyCodeError: '验证码发送错误',
    bindEmailError: '邮箱绑定错误',
    touchSubmitSuccess: '提交成功',
    touchSubmitSError: '提交失败',
    touchSubmitSuccessDesc: '我们的团队会尽快与您联系',
    signSubmitSuccess: '签名请求成功',
    signSubmitSError: '签名请求失败',
    signSubmitSuccessDesc: '请前往您的邮箱( {{productName}} ) 查看进行Dropbox签名',
    investSuccess: '投资成功',
    investSuccessDesc: '您向此产品投资了{{amount}}USDT',
    investError: '投资失败',
    notEnoughBalanceError: '您的USDT余额不足',
    getDropboxSignError: '获取Dropbox签名失败',
    approveUsdtError: '申请USDT权限失败',
    claimSuccess: '取出成功',
    claimSuccessDesc: '您从此产品池中取出了 {{amount}} USDT',
    claimError: '取出失败',
    closePoolSuccess: '产品池关闭成功',
    closePoolSuccessDesc: '产品池 {{productName}} 已经被关闭',
    closePoolError: '产品池关闭失败',
    approveBorrowerSuccess: '审批成功',
    approveBorrowerSuccessDesc: '产品池 {{productName}} 的资金已被审批转移给借款人',
    approveBorrowerError: '审批失败',
  },
  en: {
    sendVerifyCodeError: 'Verification Code Send Error',
    bindEmailError: 'Email Bind Error',
    touchSubmitSuccess: 'Submit successfully',
    touchSubmitSError: 'Submit Error',
    touchSubmitSuccessDesc: 'Our team will be in touch as soon as possible',
    signSubmitSuccess: 'Sign submit successfully',
    signSubmitSError: 'Sign submit Error',
    signSubmitSuccessDesc: 'Please go to your mailbox( {{productName}} ) to check for Dropbox signature',
    investSuccess: 'Invest successfully',
    investSuccessDesc: 'You bought the product worth {{amount}} USDT',
    investError: 'Invest Error',
    notEnoughBalanceError: 'Your USDT balance not enough',
    getDropboxSignError: 'Get dropbox signature error',
    approveUsdtError: 'Approve USDT permission error',
    claimSuccess: 'Claim successfully',
    claimSuccessDesc: 'You claim {{amount}} USDT from the product pool',
    claimError: 'Claim Error',
    closePoolSuccess: 'Close successfully',
    closePoolSuccessDesc: 'Product pool {{productName}} has been closed',
    closePoolError: 'Close Error',
    approveBorrowerSuccess: 'Approve successfully',
    approveBorrowerSuccessDesc: 'The funds of the product pool {{productName}} have been approved and transferred to the borrower',
    approveBorrowerError: 'Approve Error',
  }
}